[window]
padding.x = 15
padding.y = 15
dimensions = { columns = 90, lines = 25 }
decorations = "Full"

dynamic_title = true

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 19

[cursor.style]
blinking = "On"
shape = "Block"